### ISSUE TITLE
Logic error

### ISSUE THREAD

**Issue by DigitalPhoneme** [brady-newhard/js-functions-lab#2]
https://github.com/brady-newhard/js-functions-lab/blob/c80936aaec0948634da2d0f742b87eab37faba42/app.js#L72

The for loop version ```(isCharAVowel2)``` immediately returns ```false`` if the char being compared in the loop does not match the current ```vowelChar ``` even if it is included in the list of vowels. This is a logical error. Here is an alternative solution:

```const isCharAVowel = (char) => {
  // Convert character to lowercase
  char = char.toLowerCase();
  // Define an array of vowels
  const vowels = ['a', 'e', 'i', 'o', 'u'];
  // Check if the character is included in the array of vowels
  return vowels.includes(char);
};

console.log(isCharAVowel("a")); // true
console.log(isCharAVowel("b")); // false
```

**Comment by brady-newhard** [comment]
Corrected. Thanks for the alt solution. This looks better and more simple.
