### ISSUE TITLE
no return value for cases where all numbers are equal

### ISSUE THREAD

**Issue by DigitalPhoneme** [brady-newhard/js-functions-lab#3]
https://github.com/brady-newhard/js-functions-lab/blob/c80936aaec0948634da2d0f742b87eab37faba42/app.js#L121

You could add an else statement for the case where your numbers are all equal or you could make use of the Math.max() method.

```const maxOfThree = (num1, num2, num3) => {
  return Math.max(num1, num2, num3);
};

console.log(maxOfThree(4, 2, 0)); // 4
console.log(maxOfThree(5, 5, 5)); // 5
```

**Comment by brady-newhard** [comment]
Corrected. I added the solution to my original. This is was cleaner and more direct than mine. Thanks!
