### ISSUE TITLE
incorrect syntax

### ISSUE THREAD

**Issue by DigitalPhoneme** [brady-newhard/js-functions-lab#4]
https://github.com/brady-newhard/js-functions-lab/blob/c80936aaec0948634da2d0f742b87eab37faba42/app.js#L220

for this to work correctly, you want to use ```&&``` not ```&```

**Comment by brady-newhard** [comment]
Corrected. Typo with a copy/paste snowball. Thanks!

**Comment by brady-newhard** [comment]
Corrected. Typo with a copy/paste snowball. Thanks!
